version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    ports:
      - "8000:8000"
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api


